{% set name = "vamb" %}
{% set version = "5.0.2" %}

package:
  name: vamb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vamb-{{ version }}.tar.gz
  sha256: bfbc6819e7dc91d1caf6f1f3cb1e861e6d7782f632a6e87df9fa615bbd9e8f74

build:
  number: 0
  entry_points:
    - vamb = vamb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('vamb', max_pin="x") }}

requirements:
  host:
    - python >=3.10.0,<4
    - setuptools >=70.1,<71.dev0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.10.0,<4
    - vambcore >=0.1.2,<0.2
    - numpy >=2.2.0,<3
    - pytorch >=2.6.0,<3
    - pycoverm >=0.6.0,<0.7
    - networkx >=3.4.2,<4
    - scikit-learn >=1.6.1,<2
    - dadaptation >=3.2
    - loguru >=0.7.0,<0.8
    - pyhmmer >=0.11.0,<0.12
    - pyrodigal >=3.6.0,<4

test:
  commands:
    - vamb --help

about:
  home: https://github.com/RasmussenLab/vamb
  license: MIT License
  license_family: MIT
  summary: Variational autoencoder for metagenomic binning

extra:
  identifiers:
    - doi:10.1101/2024.10.25.620172
    - biotools:vamb
