{% set name = "vamb" %}
{% set version = "5.0.2" %}

package:
  name: vamb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vamb-{{ version }}.tar.gz
  sha256: bfbc6819e7dc91d1caf6f1f3cb1e861e6d7782f632a6e87df9fa615bbd9e8f74

build:
  number: 0
  entry_points:
    - vamb = vamb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('vamb', max_pin="x") }}

requirements:
  host:
    - python <3.14,>=3.10.0
    - setuptools >=70.1,<71.dev0
    - setuptools-scm >=8.0
    - pip
  run:
    - python <3.14,>=3.10.0
    - vambcore >=0.1.2
    - numpy >=1.26.0
    - pytorch >=2.6.0
    - pycoverm >=0.6.0
    - networkx >=3.4.0
    - scikit-learn >=1.6.0
    - dadaptation >=3.2
    - loguru >=0.7.0
    - pyhmmer >=0.10.15
    - pyrodigal >=3.6.0

test:
  commands:
    - vamb --help

about:
  home: https://github.com/RasmussenLab/vamb
  license: MIT License
  license_family: MIT
  summary: Variational autoencoder for metagenomic binning

extra:
  identifiers:
    - doi:10.1101/2024.10.25.620172
    - biotools:vamb
