{% set name = "vamb" %}
{% set version = "5.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vamb-{{ version }}.tar.gz
  sha256: 55451758eb9eaa27eade7b77b6d7bb588c8cb34cf3fe66845d6b90a87b3ba935

build:
  number: 0
  entry_points:
    - vamb = vamb.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage('vamb', max_pin="x") }}

requirements:
  host:
    - python >=3.10.0,<4
    - setuptools >=70.1,<71.dev0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.10.0,<4
    - vambcore >=0.1.2,<0.2
    - numpy >=2.2.0,<3
    - pytorch >=2.6.0,<3
    - pycoverm >=0.6.0,<0.7
    - networkx >=3.4.2,<4
    - scikit-learn >=1.6.1,<2
    - dadaptation >=3.2
    - loguru >=0.7.0,<0.8
    - pyhmmer >=0.11.0,<0.12
    - pyrodigal >=3.6.0,<4

test:
  commands:
    - vamb --help

about:
  home: https://github.com/RasmussenLab/vamb
  dev_url: https://github.com/RasmussenLab/vamb
  doc_url: "https://vamb.readthedocs.io/en/latest"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Variational autoencoder for metagenomic binning."

extra:
  identifiers:
    - doi:10.1101/2024.10.25.620172
    - biotools:vamb
